name: "BUILD Release: Windows"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.4

    - name: Build
      run: make release

    - name: Binary
      uses: actions/upload-artifact@v2
      with:
        name: Discord-RPC-Tray_windows
        path: Discord-RPC-Tray.exe
