name: "BUILD: Windows"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: true

    - name: Build
      run: make build

    - name: Binary
      uses: actions/upload-artifact@v2
      with:
        name: Windows Binary
        path: Discord-RPC-Tray.exe
